### ISSUE TITLE
NPE - change language 

### ISSUE THREAD

**Issue by tasjapr** [T8RIN/ImageToolbox#403]
1) open settings
2) press "language" button
3) app crashes with next stacktrace:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.localepicker.AppLocalePickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3834)
 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3980)
 at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
 at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
 at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2394)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loopOnce(Looper.java:211)
 at android.os.Looper.loop(Looper.java:300)
 at android.app.ActivityThread.main(ActivityThread.java:8296)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
 at com.android.settings.localepicker.AppLocalePickerActivity.onCreate(AppLocalePickerActivity.java:82)
 at android.app.Activity.performCreate(Activity.java:8523)
 at android.app.Activity.performCreate(Activity.java:8487)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1438)
 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815)
 ... 12 more

App version: 2.2.0 (75)
Phone: Xiaomi Redmi note 10 pro
Android 13
MIUI 14.0.2
System language: English

**Comment by T8RIN** [comment]
https://github.com/vtosters/lite/issues/1182

**Comment by T8RIN** [comment]
Интересно только как теперь это отловить

**Comment by T8RIN** [comment]
Fixed

**Comment by tasjapr** [comment]
Still reproducing ( 
App version 2.3.0 (84)

`java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.settings/com.android.settings.localepicker.AppLocalePickerActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3834)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3980)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2394)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8296)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
	at com.android.settings.localepicker.AppLocalePickerActivity.onCreate(AppLocalePickerActivity.java:82)
	at android.app.Activity.performCreate(Activity.java:8523)
	at android.app.Activity.performCreate(Activity.java:8487)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1438)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3815)
	... 12 more
`
