### ISSUE TITLE
[Bug] App Crash: IllegalArgumentException

### ISSUE THREAD

**Issue by Jesse205** [T8RIN/ImageToolbox#993]
**Describe the bug**

I don't know why, I don't know how to describe how this triggers. But I uploaded a video.

```txt
[Bug] App Crash: IllegalArgumentException

Device: DBY-W09 (HUAWEI - HWDBY), SDK: 31 (12), App: 2.8.0 (134)

java.lang.IllegalArgumentException: red = 0.0, green = 0.0, blue = 0.0, alpha = -3.833397E-8 outside the range for sRGB IEC61966-2.1 (id=0, model=Rgb)
	at androidx.compose.ui.graphics.a.F(SourceFile:3)
	at androidx.compose.ui.graphics.a.b(SourceFile:484)
	at r0.w.c(SourceFile:17)
	at t0.c.a(SourceFile:23)
	at t0.c.j0(SourceFile:44)
	at I0.J.j0(SourceFile:16)
	at t0.g.j(SourceFile:65)
	at t.r.a(SourceFile:587)
	at t.r.k(SourceFile:54)
	at o0.e.a(SourceFile:3)
	at I0.J.b(SourceFile:50)
	at I0.h0.I0(SourceFile:55)
	at I0.h0.G0(SourceFile:30)
	at I0.D.Y0(SourceFile:6)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at I0.D.Y0(SourceFile:6)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at I0.D.Y0(SourceFile:6)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at t.Y.b(SourceFile:257)
	at t.Y.d(SourceFile:166)
	at Q3.Z4.e(SourceFile:114)
	at i0.v.a(SourceFile:52)
	at i0.w.c(SourceFile:140)
	at I0.u0.a(SourceFile:3)
	at Y.K0.k(SourceFile:398)
	at J0.Y0.C(SourceFile:22)
	at J0.a1.i(SourceFile:40)
	at J0.a1.l(SourceFile:14)
	at I0.h0.G0(SourceFile:5)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at J0.z.dispatchDraw(SourceFile:69)
	at android.view.View.draw(View.java:23798)
	at android.view.View.updateDisplayListIfDirty(View.java:22584)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4827)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4800)
	at android.view.View.updateDisplayListIfDirty(View.java:22522)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4827)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4800)
	at android.view.View.updateDisplayListIfDirty(View.java:22522)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:549)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:555)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:641)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:6038)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5750)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4742)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3132)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11095)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1592)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1256)
	at android.view.Choreographer.doFrame(Choreographer.java:1125)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1542)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.loopProcess(ActivityThread.java:9961)
	at android.app.ActivityThread.main(ActivityThread.java:9950)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)
```

**To Reproduce**

**Expected behavior**

**Screenshots**
https://github.com/T8RIN/ImageToolbox/assets/51242302/9b8b2a62-61d7-479b-b481-54314f5791e8

**Smartphone (please complete the following information):**
 - Device: HUAWEI MatePad 11
 - OS: HarmonyOS 4.0

**Comment by T8RIN** [comment]
Should be the same as #990, this is fixed i hope, could can check the latest actions build please?

**Comment by T8RIN** [comment]
How it is?

**Comment by Jesse205** [comment]
> How it is?

I downloaded the https://github.com/T8RIN/ImageToolbox/actions/runs/8819232820 (the latest one is being built) and the bug is not resolved.

**Comment by Jesse205** [comment]
But the problem with # 990 is gone

**Comment by T8RIN** [comment]
Interesting

**Comment by T8RIN** [comment]
So, waiting for https://github.com/T8RIN/ImageToolbox/actions/runs/8819966892

**Comment by Jesse205** [comment]
> So, waiting for https://github.com/T8RIN/ImageToolbox/actions/runs/8819966892

No, it's still not.

```
[Bug] App Crash: IllegalArgumentException

Device: DBY-W09 (HUAWEI - HWDBY), SDK: 31 (12), App: 2.8.1 (136)

java.lang.IllegalArgumentException: red = 0.0, green = 0.0, blue = 0.0, alpha = -3.833397E-8 outside the range for sRGB IEC61966-2.1 (id=0, model=Rgb)
	at androidx.compose.ui.graphics.a.F(SourceFile:3)
	at androidx.compose.ui.graphics.a.b(SourceFile:484)
	at r0.v.c(SourceFile:17)
	at t0.c.a(SourceFile:23)
	at t0.c.i0(SourceFile:44)
	at I0.J.i0(SourceFile:16)
	at t0.g.j(SourceFile:65)
	at t.r.a(SourceFile:587)
	at t.r.n(SourceFile:54)
	at o0.e.a(SourceFile:3)
	at I0.J.b(SourceFile:50)
	at I0.h0.I0(SourceFile:55)
	at I0.h0.G0(SourceFile:30)
	at I0.D.Y0(SourceFile:6)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at I0.D.Y0(SourceFile:6)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at I0.D.Y0(SourceFile:6)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at t.Y.b(SourceFile:257)
	at t.Y.d(SourceFile:166)
	at F3.Z4.e(SourceFile:114)
	at i0.w.a(SourceFile:52)
	at i0.x.c(SourceFile:140)
	at I0.u0.a(SourceFile:3)
	at Y.L0.n(SourceFile:416)
	at J0.X0.A(SourceFile:22)
	at J0.a1.i(SourceFile:40)
	at J0.a1.l(SourceFile:14)
	at I0.h0.G0(SourceFile:5)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at J0.z.dispatchDraw(SourceFile:69)
	at android.view.View.draw(View.java:23798)
	at android.view.View.updateDisplayListIfDirty(View.java:22584)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4827)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4800)
	at android.view.View.updateDisplayListIfDirty(View.java:22522)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4827)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4800)
	at android.view.View.updateDisplayListIfDirty(View.java:22522)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:549)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:555)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:641)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:6038)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5750)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4742)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3132)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11095)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1592)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1256)
	at android.view.Choreographer.doFrame(Choreographer.java:1125)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1542)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.loopProcess(ActivityThread.java:9961)
	at android.app.ActivityThread.main(ActivityThread.java:9950)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)

```

**Comment by Jesse205** [comment]
> Hmmm, So, maybe this? https://github.com/T8RIN/ImageToolbox/actions/runs/8820875307

```
[Bug] App Crash: IllegalArgumentException

Device: DBY-W09 (HUAWEI - HWDBY), SDK: 31 (12), App: 2.8.1 (136)

java.lang.IllegalArgumentException: red = 0.0, green = 0.0, blue = 0.0, alpha = -3.833397E-8 outside the range for sRGB IEC61966-2.1 (id=0, model=Rgb)
	at androidx.compose.ui.graphics.a.F(SourceFile:3)
	at androidx.compose.ui.graphics.a.b(SourceFile:484)
	at r0.v.c(SourceFile:17)
	at t0.c.a(SourceFile:23)
	at t0.c.i0(SourceFile:44)
	at I0.J.i0(SourceFile:16)
	at t0.g.j(SourceFile:65)
	at t.r.a(SourceFile:587)
	at t.r.n(SourceFile:54)
	at o0.e.a(SourceFile:3)
	at I0.J.b(SourceFile:50)
	at I0.h0.I0(SourceFile:55)
	at I0.h0.G0(SourceFile:30)
	at I0.D.Y0(SourceFile:6)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at I0.D.Y0(SourceFile:6)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at I0.D.Y0(SourceFile:6)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at t.Y.b(SourceFile:257)
	at t.Y.d(SourceFile:166)
	at F3.Z4.e(SourceFile:114)
	at i0.w.a(SourceFile:52)
	at i0.x.c(SourceFile:140)
	at I0.u0.a(SourceFile:3)
	at Y.L0.n(SourceFile:416)
	at J0.X0.A(SourceFile:22)
	at J0.a1.i(SourceFile:40)
	at J0.a1.l(SourceFile:14)
	at I0.h0.G0(SourceFile:5)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at I0.y.Y0(SourceFile:28)
	at I0.h0.I0(SourceFile:9)
	at I0.h0.G0(SourceFile:30)
	at androidx.compose.ui.node.a.i(SourceFile:5)
	at J0.z.dispatchDraw(SourceFile:69)
	at android.view.View.draw(View.java:23798)
	at android.view.View.updateDisplayListIfDirty(View.java:22584)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4827)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4800)
	at android.view.View.updateDisplayListIfDirty(View.java:22522)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4827)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4800)
	at android.view.View.updateDisplayListIfDirty(View.java:22522)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:549)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:555)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:641)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:6038)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5750)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4742)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3132)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11095)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1592)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1256)
	at android.view.Choreographer.doFrame(Choreographer.java:1125)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1542)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.loopProcess(ActivityThread.java:9961)
	at android.app.ActivityThread.main(ActivityThread.java:9950)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1240)

```
